ALTER TABLE par_usuarios ADD COLUMN password CHARACTER VARYING(64) NOT NULL DEFAULT 'LOCKED';
ALTER TABLE par_usuarios ADD COLUMN readonly BOOLEAN NOT NULL DEFAULT TRUE;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2021-05-30');
