<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="https://sis.SERMEPA.es/sis/InotificacionSIS.wsdl" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="InotificacionSIS" targetNamespace="https://sis.SERMEPA.es/sis/InotificacionSIS.wsdl">
	<message name="procesaNotificacionSISRequest">
		<part name="XML" type="xs:string"/>
	</message>
	<message name="procesaNotificacionSISResponse">
		<part name="return" type="xs:string"/>
	</message>
	<portType name="InotificacionSISPortType">
		<operation name="procesaNotificacionSIS">
			<input message="tns:procesaNotificacionSISRequest"/>
			<output message="tns:procesaNotificacionSISResponse"/>
		</operation>
	</portType>
	<binding name="InotificacionSISBinding" type="tns:InotificacionSISPortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="procesaNotificacionSIS">
			<soap:operation soapAction="urn:InotificacionSIS#procesaNotificacionSIS" style="rpc"/>
			<input>
				<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="InotificacionSIS" use="encoded"/>
			</input>
			<output>
				<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="InotificacionSIS" use="encoded"/>
			</output>
		</operation>
	</binding>
	<service name="InotificacionSISService">
		<port binding="tns:InotificacionSISBinding" name="InotificacionSIS">
			<soap:address location="http://localhost:8080/uji-par-web-benicassim/services/InotificacionSIS"/>
		</port>
	</service>
</definitions>
